version: '3.1'

services:
  postgres:
    image: postgres:13  # You can change the version as needed
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '3307:5432'  # Exposing PostgreSQL default port (5432) on 3307
    expose:
      - '5432'
    networks:
      - mired
  microservice:
    image: microservice
    ports:
      - '8080:8080'
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - mired
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/db?autoReconnect=true&useSSL=false
      DATABASE_USER: user
      DATABASE_PASSWORD: password
networks:
  mired:
    driver: bridge