services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '3307:5432'
    expose:
      - '5432'
    networks:
      - mired

  pica_microservice:
    image: microservice
    ports:
      - '8087:8083'
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - mired
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/db?autoReconnect=true&useSSL=false
      DATABASE_USER: user
      DATABASE_PASSWORD: password

networks:
  mired:
    driver: bridge