# microservice-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
        - name: authorization
          image: knimisica/authorization:latest
          envFrom:
            - configMapRef:
                name: authorization-secret
          ports:
            - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: authorization
spec:
  selector:
    app: authorization
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
